server:
  port: 9099
spring:
  application:
    name: transfer-service
  datasource:
    password: lixin
    username: lixin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.153.125:3306/lixin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000
  cloud:
    loadbalancer:
      retry:
        enabled: true
user-service:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10002/eureka,http://localhost:10001/eureka
mybatis:
  mapper-locations:
    - mybatis/mapper/*/*
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000 # 设置hystrix的超时时间为6000ms